### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by nortonjco1** [hassio-addons/addon-bookstack#154]
# Problem/Motivation

> unable to login

## Expected behavior

> ability to login

## Actual behavior

> Get unknown error occured, return to homepage

## Steps to reproduce

> click on login and attempt to login

## Proposed changes

I'm using bookstack and it is configured to update automatically. Today I tried to login and it returns Unknown Error.

It is Current version: 0.13.3

**Comment by sinclairpaul** [comment]
Without any logs, or browser console output, it is difficult to help.

Initially I would suggest clearing any cookies or cache related to the site.

**Comment by nortonjco1** [comment]
logs are showing:  

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] bookstack: applying... 
[fix-attrs.d] bookstack: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Bookstack
 Simple & Free Wiki Software
-----------------------------------------------------------
 Add-on version: 0.13.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.8.8
 Home Assistant Supervisor: 2021.10.8
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] bookstack.sh: executing... 
[11:08:10] WARNING: Bookstack is using the Maria DB addon
[11:08:10] WARNING: Please ensure this is included in your backups
[11:08:10] WARNING: Uninstalling the MariaDB addon will remove any data
[11:08:10] INFO: Creating database for Bookstack if required
[cont-init.d] bookstack.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:08:13] INFO: Installing/updating Database
Migrating: 2021_05_15_173110_create_favourites_table
   UnexpectedValueException  : The stream or file "/var/www/bookstack/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: No such file or directory
  at /var/www/bookstack/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:146
    142|             restore_error_handler();
    143|             if (!is_resource($stream)) {
    144|                 $this->stream = null;
    145| 
  > 146|                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened in append mode: '.$this->errorMessage, $url));
    147|             }
    148|             stream_set_chunk_size($stream, $this->streamChunkSize);
    149|             $this->stream = $stream;
    150|         }
  Exception trace:
  1   Monolog\Handler\StreamHandler::write()
      /var/www/bookstack/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:48
  2   Monolog\Handler\AbstractProcessingHandler::handle()
      /var/www/bookstack/vendor/monolog/monolog/src/Monolog/Logger.php:327
  Please use the argument -v to see more details.
[11:08:14] INFO: Starting PHP-FPM...
[11:08:14] INFO: Starting NGinx...

**Comment by nortonjco1** [comment]
This is what the browser shows after trying to login:
![Capture](https://user-images.githubusercontent.com/22178174/140153316-64f69979-ded4-4a64-8581-b340b3b5b4a7.JPG)

**Comment by nortonjco1** [comment]
Additionally, cleared everything in Chrome and tried FireFox, Edge. Also tried another system (Chrome, Firefox and Safari). Same error

**Comment by nortonjco1** [comment]
Bookstack seems to work fine otherwise, just can't login to do any edits.

**Comment by sinclairpaul** [comment]
So this `UnexpectedValueException : The stream or file "/var/www/bookstack/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: No such file or directory`

Is an error being thrown, but there is an issue which means it can't be written.

I'll push a release to show the error, however it is likely that there isn't anything that can be done here, and will likely need to be investigated upstream.

**Comment by nortonjco1** [comment]
So, you think I need to backup the database and restore? Or is the backup going to have a problem. 

Seems to work fine other than I can't log in. BTW, the error appears in the log even if you don't try to log in.

**Comment by sinclairpaul** [comment]
I have pushed a new release so the error should be shown.  The error will only be thrown on the addon startup.

I can't tell you the issue, all I can say is that there appears to be issues for the database scripts applying.  The restore suggestion is to perform a restore to a point where it was working ok (assuming you have a backup).

**Comment by nortonjco1** [comment]
I have backups, I restored one bringing bookstack back to 13.0, but the error is still there and can't login.

**Comment by nortonjco1** [comment]
I found another really old backup from September which brought bookstack to 0.12.1

I can log into it. In the logs, I see that error as before.


[17:46:31] INFO: Installing/updating Database
Migrating: 2021_05_15_173110_create_favourites_table
   UnexpectedValueException  : The stream or file "/var/www/bookstack/storage/logs/laravel.log" could not be opened in append mode: failed to open stream: No such file or directory
  at /var/www/bookstack/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:119
    115|             restore_error_handler();
    116|             if (!is_resource($stream)) {
    117|                 $this->stream = null;
    118| 
  > 119|                 throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened in append mode: '.$this->errorMessage, $url));
    120|             }
    121|             stream_set_chunk_size($stream, self::MAX_CHUNK_SIZE);
    122|             $this->stream = $stream;
    123|         }
  Exception trace:
  1   Monolog\Handler\StreamHandler::write()
      /var/www/bookstack/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php:48
  2   Monolog\Handler\AbstractProcessingHandler::handle()
      /var/www/bookstack/vendor/monolog/monolog/src/Monolog/Logger.php:326
  Please use the argument -v to see more details.

**Comment by sinclairpaul** [comment]
Restore the Database, i.e. MariaDB, install the latest Bookstack addon.

**Comment by sinclairpaul** [comment]
From looking around at possible similar issues (https://github.com/BookStackApp/BookStack/issues/3009).

What you may be able to do is:

Install the phpMyAdmin addon from the Community store.

Take a backup of the database (should be named bookstack), either from a snapshot, or within the phpmyadmin app.

Select the favourites table in the database:

![image](https://user-images.githubusercontent.com/24625998/140237325-b54fd043-4ed4-4edb-a52d-5b3bacbc090c.png)

Choose Operations:

![image](https://user-images.githubusercontent.com/24625998/140237374-a187b9f0-444f-4532-a63e-601d22a08b4d.png)

Then Drop the table:

![image](https://user-images.githubusercontent.com/24625998/140237399-ca359202-d5f5-42b8-a8ee-c79cab075fc0.png)


As per the issue, you may have to do the same with the mfa_values table, and this may lead to lose of data.

**Comment by nortonjco1** [comment]
Tried those items:

I don't have a favourites nor a mfa_values:

![image](https://user-images.githubusercontent.com/22178174/140243683-9f39b4ac-6b4a-4a50-9d51-d077beddb555.png)

But I backed up the bookstack database, uninstalled bookstack, reinstalled, imported the backup.

Database loaded, but still get same error when trying to login.

Should I remove MariaDB from my system as well and try reloading?

**Comment by nortonjco1** [comment]
Posted the above too soon. One more restart and it seems to be working.

**Comment by nortonjco1** [comment]
ok. So, I restored bookstack from my backup that had the 0.13.0 version. Validated that I had the images.

Could not log in.

Updated bookstack to 0.13.4

Was able to log in!

Thanks Paul.

**Comment by sinclairpaul** [comment]
Glad you got it working!
